version: '3'

services:
  db:
    build:
      context: "./docker/db"
      dockerfile: Dockerfile
    container_name: mysql_host
    command: mysqld
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - container-network

  web:
    container_name: django_host
    build:
      context: "./docker/django"
      dockerfile: Dockerfile
    command: >
      bash -c "curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod u+x ./wait-for-it.sh &&
      ./wait-for-it.sh mysql_host:3306 -t 30 &&
      python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    networks:
      - container-network
    depends_on:
      - db

# Network
networks:
  container-network:
    driver: bridge
