version: '3'

services:
  web:
    build:
      context: "./docker/django"
      dockerfile: Dockerfile_with_Apache
    command: >
      bash -c "curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod u+x ./wait-for-it.sh &&
      ./wait-for-it.sh mysql_host:3306 -t 30 &&
      a2enconf django_sample.conf &&
      python manage.py runserver 0.0.0.0:8080"
    ports:
      - "80:80"
